const a8q=(s,r=document)=>r.querySelector(s),a8qa=(s,r=document)=>[...r.querySelectorAll(s)];
const a8e=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const a8n=v=>Intl.NumberFormat('en-US',{notation:Number(v)>=100000?'compact':'standard',maximumFractionDigits:1}).format(Number(v||0));
const a8Metrics={views:{label:'Views',short:'Views'},reach:{label:'Reach / impressions',short:'Reach'},likes:{label:'Likes / reactions',short:'Likes'},comments:{label:'Comments',short:'Comments'},shares:{label:'Shares / reposts',short:'Shares'},engagements:{label:'Engagements',short:'Engagements'},watch:{label:'Watch time',short:'Watch min'}};
const a8ProviderMeta={youtube:['▶','YouTube','var(--ds-provider-youtube)'],linkedin:['in','LinkedIn','var(--ds-provider-linkedin)'],telegram:['➤','Telegram','var(--ds-provider-telegram)'],facebook:['f','Facebook','var(--ds-provider-facebook)'],instagram:['◎','Instagram','var(--ds-provider-instagram)'],tiktok:['♪','TikTok','var(--ds-provider-tiktok)'],vk:['VK','VK','var(--ds-provider-vk)'],x:['X','X','var(--ds-provider-x)']};
const a8FallbackColors=['#6b5cff','#c13584','#0a66c2','#229ed9','#0077ff','#d84b39','#151515','#5b8f39'];
let A8=null,a8Metric='views',a8ChannelSet=new Set(),a8Filters={period:'30',theme:'all',format:'all',group:'day'};
const a8Route=()=>location.hash.replace('#/','')||'dashboard';

async function a8Load(){try{const r=await fetch('/api/state',{cache:'no-store'});if(r.ok)A8=await r.json()}catch{}}
function a8Channel(id){return A8?.channels?.find(c=>c.id===id)}
function a8Content(id){return A8?.content?.find(c=>c.id===id)}
function a8Topic(id){return A8?.topics?.find(t=>t.id===id)}
function a8ProviderColor(channel,index=0){const provider=channel?.provider;return a8ProviderMeta[provider]?.[2]||a8FallbackColors[index%a8FallbackColors.length]}
function a8ProviderLabel(channel){const m=a8ProviderMeta[channel?.provider]||['•',channel?.provider||'Channel'];return `${m[0]} ${channel?.label||m[1]}`}
function a8MetricValue(s,key){const raw=s.raw||{},norm=s.normalized||{};if(key==='views')return Number(norm.views||raw.views||0);if(key==='reach')return Number(raw.reach||norm.impressions||raw.impressions||0);if(key==='likes')return Number(raw.likes||raw.reactions||0);if(key==='comments')return Number(raw.comments||0);if(key==='shares')return Number(raw.shares||raw.reposts||0);if(key==='engagements')return Number(norm.engagements||raw.engagements||Number(raw.likes||raw.reactions||0)+Number(raw.comments||0)+Number(raw.shares||raw.reposts||0));if(key==='watch')return Number(norm.watchMinutes||raw.watchMinutes||0);return 0}
function a8Start(){if(a8Filters.period==='all')return null;const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-Number(a8Filters.period)+1);return d}
function a8WeekStart(v){const d=new Date(v),day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);d.setHours(0,0,0,0);return d}
function a8BucketKey(v){const d=new Date(v);if(a8Filters.group==='month')return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;if(a8Filters.group==='week')return a8WeekStart(d).toISOString().slice(0,10);return d.toISOString().slice(0,10)}
function a8BucketLabel(key){if(a8Filters.group==='month'){const [y,m]=key.split('-').map(Number);return new Intl.DateTimeFormat('en-US',{month:'short',year:'numeric'}).format(new Date(y,m-1,1))}return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(new Date(`${key}T12:00:00`))}
function a8BaseSnapshots(){return A8?.dashboard?.analytics?.snapshots||A8?.analyticsSnapshots||[]}
function a8Hash(s){let h=2166136261;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return Math.abs(h>>>0)}
function a8DemoSnapshots(){
  const channels=(A8?.channels||[]).slice(0,8);if(!channels.length)return [];
  const days=90,out=[];const now=new Date();now.setHours(12,0,0,0);
  channels.forEach((ch,ci)=>{const seed=a8Hash(ch.id);for(let i=days-1;i>=0;i--){const d=new Date(now);d.setDate(d.getDate()-i);const progress=(days-i)/days;const wave=1+Math.sin((i+ci*3)/4)*.18+Math.cos((i+ci)/7)*.11;const base=(140+ci*95)*(0.32+progress*1.9)*wave;const views=Math.max(0,Math.round(base+(seed%70)));const reach=Math.round(views*(1.35+(ci%3)*.12));const likes=Math.round(views*(.035+(ci%4)*.006));const comments=Math.max(0,Math.round(likes*(.12+(ci%2)*.04)));const shares=Math.max(0,Math.round(likes*(.07+(ci%3)*.02)));const watch=Math.round(views*(ci%3===0?2.7:.55));out.push({id:`a8-${ch.id}-${i}`,contentId:null,channelId:ch.id,provider:ch.provider,capturedAt:d.toISOString(),raw:{views,reach,impressions:reach,likes,reactions:likes,comments,shares,watchMinutes:watch},normalized:{views,impressions:reach,engagements:likes+comments+shares,watchMinutes:watch},__demo:true})}});return out
}
function a8Snapshots(){const actual=a8BaseSnapshots(),channelCount=new Set(actual.map(s=>s.channelId)).size;return actual.length>=14&&channelCount>=2?actual:a8DemoSnapshots()}
function a8Matches(s){const start=a8Start(),d=new Date(s.capturedAt);if(start&&d<start)return false;if(a8ChannelSet.size&&!a8ChannelSet.has(s.channelId))return false;const c=a8Content(s.contentId);if(a8Filters.theme!=='all'&&c?.topicId!==a8Filters.theme)return false;if(a8Filters.format!=='all'&&c?.type!==a8Filters.format)return false;return true}
function a8Filtered(){return a8Snapshots().filter(a8Matches)}
function a8SelectedChannels(){const all=A8?.channels||[];return a8ChannelSet.size?all.filter(c=>a8ChannelSet.has(c.id)):all}
function a8Buckets(snaps){
  const rows=[];let start=a8Start(),end=new Date();end.setHours(0,0,0,0);if(!start){const ds=snaps.map(s=>new Date(s.capturedAt)).filter(d=>!Number.isNaN(d.getTime()));start=ds.length?new Date(Math.min(...ds.map(d=>d.getTime()))):new Date(end);if(!ds.length)start.setDate(start.getDate()-29);start.setHours(0,0,0,0)}
  if(a8Filters.group==='month'){let cur=new Date(start.getFullYear(),start.getMonth(),1),last=new Date(end.getFullYear(),end.getMonth(),1);while(cur<=last){rows.push(`${cur.getFullYear()}-${String(cur.getMonth()+1).padStart(2,'0')}`);cur=new Date(cur.getFullYear(),cur.getMonth()+1,1)}}else if(a8Filters.group==='week'){let cur=a8WeekStart(start),last=a8WeekStart(end);while(cur<=last){rows.push(cur.toISOString().slice(0,10));cur.setDate(cur.getDate()+7)}}else{let cur=new Date(start);while(cur<=end){rows.push(cur.toISOString().slice(0,10));cur.setDate(cur.getDate()+1)}}
  return rows
}
function a8Series(){const snaps=a8Filtered(),keys=a8Buckets(snaps),channels=a8SelectedChannels();const byChannel=new Map(channels.map(ch=>[ch.id,new Map(keys.map(k=>[k,0]))]));for(const s of snaps){if(!byChannel.has(s.channelId))continue;const k=a8BucketKey(s.capturedAt);if(!byChannel.get(s.channelId).has(k))byChannel.get(s.channelId).set(k,0);byChannel.get(s.channelId).set(k,byChannel.get(s.channelId).get(k)+a8MetricValue(s,a8Metric))}return {snaps,keys,series:channels.map((ch,i)=>({channel:ch,color:a8ProviderColor(ch,i),values:keys.map(k=>Number(byChannel.get(ch.id)?.get(k)||0))}))}}
function a8NiceMax(value){if(!Number.isFinite(value)||value<=0)return 10;const target=value*1.08,exp=Math.pow(10,Math.floor(Math.log10(target))),f=target/exp;const nice=f<=1?1:f<=2?2:f<=5?5:10;return nice*exp}
function a8AxisLabel(v){if(v>=1000000)return `${Number((v/1000000).toFixed(v>=10000000?0:1))}M`;if(v>=1000)return `${Number((v/1000).toFixed(v>=10000?0:1))}K`;return String(Math.round(v))}
function a8Chart(keys,series){
  if(!keys.length||!series.length)return '<div class="analytics-chart-empty">No analytics data for the current filters.</div>';
  const W=1280,H=520,left=118,right=30,top=34,bottom=78,iw=W-left-right,ih=H-top-bottom,maxRaw=Math.max(0,...series.flatMap(s=>s.values)),max=a8NiceMax(maxRaw),steps=5;
  const x=i=>left+(keys.length<=1?iw/2:(i/(keys.length-1))*iw),y=v=>top+ih-(v/max)*ih;
  const yGrid=Array.from({length:steps+1},(_,i)=>{const val=(max/steps)*i,yy=y(val);return `<g><line class="analytics-chart-grid" x1="${left}" x2="${W-right}" y1="${yy}" y2="${yy}"/><text class="analytics-axis-label" text-anchor="end" x="${left-18}" y="${yy+7}">${a8e(a8AxisLabel(val))}</text></g>`}).join('');
  const every=Math.max(1,Math.ceil(keys.length/7)),xTicks=keys.map((k,i)=>(i%every===0||i===keys.length-1)?`<text class="analytics-axis-label" text-anchor="middle" x="${x(i)}" y="${H-24}">${a8e(a8BucketLabel(k))}</text>`:'').join('');
  const lines=series.map((s,si)=>{const pts=s.values.map((v,i)=>`${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(' ');const dots=s.values.map((v,i)=>`<circle class="analytics-series-point" style="fill:${s.color};stroke:${s.color}" cx="${x(i)}" cy="${y(v)}" r="4"><title>${a8e(s.channel.label)} · ${a8e(a8BucketLabel(keys[i]))}: ${a8e(a8n(v))}</title></circle>`).join('');return `<polyline class="analytics-series-line" style="stroke:${s.color}" points="${pts}"/>${dots}`}).join('');
  const overlays=keys.map((_,i)=>{const x0=i===0?left:(x(i-1)+x(i))/2,x1=i===keys.length-1?W-right:(x(i)+x(i+1))/2;return `<rect class="analytics-hover-target" data-a8-index="${i}" x="${x0}" y="${top}" width="${Math.max(1,x1-x0)}" height="${ih}"/>`}).join('');
  return `<div class="analytics-chart-canvas"><svg data-a8-chart viewBox="0 0 ${W} ${H}" role="img" aria-label="${a8e(a8Metrics[a8Metric].label)} by selected channels">${yGrid}<text class="analytics-y-title" x="${left}" y="20">${a8e(a8Metrics[a8Metric].short)}</text>${lines}<line data-a8-crosshair class="analytics-crosshair" x1="${left}" x2="${left}" y1="${top}" y2="${top+ih}"/>${overlays}${xTicks}</svg><div data-a8-tooltip class="analytics-chart-tooltip" hidden></div></div>`
}
function a8Totals(snaps){const t={views:0,reach:0,likes:0,comments:0,shares:0,engagements:0,watch:0};for(const s of snaps)for(const k of Object.keys(t))t[k]+=a8MetricValue(s,k);return t}
function a8Summary(keys,series){const combined=keys.map((_,i)=>series.reduce((sum,s)=>sum+s.values[i],0)),total=combined.reduce((a,b)=>a+b,0),peak=Math.max(...combined,0),peakIndex=combined.indexOf(peak),channelTotals=series.map(s=>({s,total:s.values.reduce((a,b)=>a+b,0)})).sort((a,b)=>b.total-a.total);return {total,avg:keys.length?total/keys.length:0,peak,peakLabel:peakIndex>=0?`${a8BucketLabel(keys[peakIndex])} · ${a8n(peak)}`:'—',leader:channelTotals[0]?.s.channel.label||'—'}}
function a8ProviderFilter(){const allActive=!a8ChannelSet.size;return `<div class="analytics-channel-filter" aria-label="Channels"><button data-a8-channel="all" class="all ${allActive?'active':''}">All channels</button>${(A8?.channels||[]).map((ch,i)=>`<button data-a8-channel="${a8e(ch.id)}" class="${a8ChannelSet.has(ch.id)?'active':''}"><i style="background:${a8ProviderColor(ch,i)}"></i><span>${a8e(a8ProviderMeta[ch.provider]?.[1]||ch.label)}</span></button>`).join('')}</div>`}
function a8PublishedCount(){const start=a8Start();return (A8?.content||[]).filter(c=>{if(c.status!=='published')return false;const d=new Date(c.publishedAt||c.updatedAt||c.createdAt);if(start&&d<start)return false;if(a8Filters.theme!=='all'&&c.topicId!==a8Filters.theme)return false;if(a8Filters.format!=='all'&&c.type!==a8Filters.format)return false;if(a8ChannelSet.size&&!c.targetChannelIds?.some(id=>a8ChannelSet.has(id)))return false;return true}).length}
function a8Breakdown(series){return series.slice().sort((a,b)=>b.values.reduce((x,y)=>x+y,0)-a.values.reduce((x,y)=>x+y,0)).map((s,i)=>`<div class="analytics-breakdown-row"><div><b><i class="analytics-legend-dot" style="background:${s.color}"></i>${a8e(s.channel.label)}</b><span>${a8e(a8Metrics[a8Metric].short)}</span></div><b>${a8n(s.values.reduce((x,y)=>x+y,0))}</b></div>`).join('')}
function a8Render(){
  if(!A8||a8Route()!=='analytics')return;const view=a8q('#view');if(!view)return;const {snaps,keys,series}=a8Series(),totals=a8Totals(snaps),summary=a8Summary(keys,series),period=a8Filters.period==='all'?'All recorded history':`Last ${a8Filters.period} days`,demo=a8Snapshots().some(s=>s.__demo);
  view.innerHTML=`<div class="page-head"><div><h1>Analytics</h1><p>Compare performance over time across several channels. Select any combination of channels and one metric; the vertical scale adjusts automatically to the visible data.</p></div><div class="page-meta"><span class="pill accent">${a8e(period)}</span>${demo?'<span class="pill">Demo analytics data</span>':''}</div></div>
  <div class="v3-filterbar analytics-filterbar"><label><span>Period</span><select id="a8Period"><option value="all" ${a8Filters.period==='all'?'selected':''}>All history</option>${[['7','7 days'],['30','30 days'],['90','90 days'],['365','1 year']].map(([v,l])=>`<option value="${v}" ${a8Filters.period===v?'selected':''}>${l}</option>`).join('')}</select></label><label><span>Theme</span><select id="a8Theme"><option value="all">All themes</option>${(A8.topics||[]).map(t=>`<option value="${a8e(t.id)}" ${a8Filters.theme===t.id?'selected':''}>${a8e(t.name)}</option>`).join('')}</select></label><label><span>Format</span><select id="a8Format"><option value="all">All formats</option>${[['post','Post'],['image_post','Image post'],['short','Short'],['reel','Reel'],['long_video','Long video']].map(([v,l])=>`<option value="${v}" ${a8Filters.format===v?'selected':''}>${l}</option>`).join('')}</select></label><label><span>Aggregation</span><select id="a8Group">${[['day','Day'],['week','Week'],['month','Month']].map(([v,l])=>`<option value="${v}" ${a8Filters.group===v?'selected':''}>${l}</option>`).join('')}</select></label></div>
  <section class="analytics-channel-selector"><div><span class="eyebrow">CHANNELS</span><p>Select one, several, or all channels. Each selected channel keeps its own line.</p></div>${a8ProviderFilter()}</section>
  <div class="analytics-shell"><div class="analytics-hero"><section class="analytics-chart-panel"><div class="analytics-chart-head"><div><span class="eyebrow">TREND</span><h2>${a8e(a8Metrics[a8Metric].label)}</h2><p>${a8e(period)} · ${a8e(a8Filters.group)} aggregation · Y-axis auto 0–${a8e(a8AxisLabel(a8NiceMax(Math.max(0,...series.flatMap(s=>s.values)))))}</p></div><span class="pill">${series.length} channel${series.length===1?'':'s'}</span></div><div class="analytics-metric-switch">${Object.entries(a8Metrics).map(([k,d])=>`<button data-a8-metric="${k}" class="${a8Metric===k?'active':''}">${a8e(d.short)}</button>`).join('')}</div><div class="analytics-series-legend">${series.map((s,i)=>`<span><i style="background:${s.color}"></i>${a8e(s.channel.label)}</span>`).join('')}</div><div class="analytics-chart-wrap">${a8Chart(keys,series)}</div></section><aside class="analytics-summary-panel"><span class="eyebrow">SELECTED METRIC</span><h2>${a8e(a8Metrics[a8Metric].label)}</h2><p>Summary for the same period, channel selection, theme and format as the graph.</p><div class="analytics-summary-main"><span>Total</span><b>${a8n(summary.total)}</b></div><div class="analytics-summary-list"><div class="analytics-summary-row"><span>Average per ${a8e(a8Filters.group)}</span><b>${a8n(summary.avg)}</b></div><div class="analytics-summary-row"><span>Peak ${a8e(a8Filters.group)}</span><b>${a8e(summary.peakLabel)}</b></div><div class="analytics-summary-row"><span>Leading channel</span><b>${a8e(summary.leader)}</b></div><div class="analytics-summary-row"><span>Published posts</span><b>${a8PublishedCount()}</b></div><div class="analytics-summary-row"><span>Visible channels</span><b>${series.length}</b></div><div class="analytics-summary-row"><span>Analytics points</span><b>${snaps.length}</b></div></div></aside></div>
  <div class="analytics-kpi-grid">${[['Views',totals.views],['Reach',totals.reach],['Likes',totals.likes],['Comments',totals.comments],['Shares',totals.shares],['Watch min',totals.watch]].map(([l,v])=>`<article class="analytics-kpi"><span>${l}</span><b>${a8n(v)}</b></article>`).join('')}</div>
  <div class="analytics-breakdown-grid"><section class="analytics-breakdown-panel"><h2>Selected channels</h2>${a8Breakdown(series)||'<div class="empty">No channel data.</div>'}</section><section class="analytics-breakdown-panel"><h2>How to read the graph</h2><div class="analytics-explainer"><p>The Y-axis always starts at zero and expands to a rounded upper bound based on the largest visible value.</p><p>Hover any date to compare all selected channel lines at that point.</p><p>Changing metric, period, aggregation, theme, format or channels recalculates both the graph and the summary.</p></div></section></div></div>`;
  view.dataset.analyticsV8='1';a8Bind();
}
function a8Bind(){
  a8qa('[data-a8-metric]').forEach(b=>b.onclick=()=>{a8Metric=b.dataset.a8Metric;a8Render()});
  const selects={a8Period:'period',a8Theme:'theme',a8Format:'format',a8Group:'group'};for(const [id,key] of Object.entries(selects))a8q('#'+id)?.addEventListener('change',ev=>{a8Filters[key]=ev.target.value;a8Render()});
  a8qa('[data-a8-channel]').forEach(b=>b.onclick=()=>{const id=b.dataset.a8Channel;if(id==='all'){a8ChannelSet.clear()}else if(!a8ChannelSet.size){a8ChannelSet.add(id)}else if(a8ChannelSet.has(id)){a8ChannelSet.delete(id)}else{a8ChannelSet.add(id)}a8Render()});
  a8BindHover();
}
function a8BindHover(){const svg=a8q('[data-a8-chart]'),tooltip=a8q('[data-a8-tooltip]'),cross=a8q('[data-a8-crosshair]');if(!svg||!tooltip||!cross)return;const {keys,series}=a8Series(),W=1280,left=118,right=30,iw=W-left-right,x=i=>left+(keys.length<=1?iw/2:(i/(keys.length-1))*iw);a8qa('.analytics-hover-target',svg).forEach(target=>{target.addEventListener('pointerenter',show);target.addEventListener('pointermove',show)});svg.addEventListener('pointerleave',()=>{tooltip.hidden=true;cross.style.opacity='0'});function show(ev){const i=Number(ev.currentTarget.dataset.a8Index);if(!Number.isFinite(i))return;const xx=x(i);cross.setAttribute('x1',xx);cross.setAttribute('x2',xx);cross.style.opacity='1';const values=series.map(s=>`<div><span><i style="background:${s.color}"></i>${a8e(s.channel.label)}</span><b>${a8n(s.values[i])}</b></div>`).join('');tooltip.innerHTML=`<strong>${a8e(a8BucketLabel(keys[i]))}</strong>${values}`;tooltip.hidden=false;tooltip.style.left=`${Math.max(12,Math.min(88,(xx/W)*100))}%`;tooltip.style.top='42px'}}
async function a8Apply(){if(!A8)await a8Load();if(a8Route()==='analytics')a8Render()}
window.addEventListener('hashchange',()=>setTimeout(a8Apply,110));
const a8Observer=new MutationObserver(()=>queueMicrotask(()=>{if(a8Route()==='analytics'&&A8&&a8q('#view')?.dataset.analyticsV8!=='1')a8Render()}));a8Observer.observe(document.documentElement,{subtree:true,childList:true});
setTimeout(a8Apply,140);
